version: '3.5'

networks:
  localdev:
    name: localdev
    
services:
  db-server:
    image: microsoft/mssql-server-linux:2017-latest
    container_name: db-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Emily1234
      - MSSQL_TCP_PORT=1433
    ports:
      - "1400:1433"
    networks:
      - localdev

  main-api:
    build: NetReactCrud/
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7000:80"
    depends_on:
      - db-server
    networks:
      - localdev

  react-frontend:
      build: react-app/
      restart: always
      ports:
        - "3000:3000"
      depends_on:
        - main-api
      networks:
        - localdev

