version: '3.5'

networks:
  localdev:
    name: localdev
    
services:
  db-server:
    image: postgres
    container_name: db-server
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=Emily1234
      - POSTGRES_DB=DonationDB
    ports:
      - "5432:5432"
    networks:
      - localdev

  main-api:
    build: NetReactCrud/
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7000:80"
    depends_on:
      - db-server
    networks:
      - localdev

  react-frontend:
      build: react-app/
      restart: always
      ports:
        - "3000:3000"
      depends_on:
        - main-api
      networks:
        - localdev

